# Generated by Django 5.0.7 on 2025-05-25 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Araneae_main', '0001_initial'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_hash', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('node_hash', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('HDID', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unreachable', 'Unreachable')], default='inactive', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=5000)),
                ('rpc_url', models.URLField(null=True)),
                ('auth_key', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_info', models.TextField(blank=True, null=True)),
                ('memory_info', models.TextField(blank=True, null=True)),
                ('last_active_time', models.DateTimeField(blank=True, null=True)),
                ('celery_queue', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeCurrentStatus',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Araneae_manager.node')),
                ('cpu_percent', models.FloatField()),
                ('memory_used', models.BigIntegerField()),
                ('memory_total', models.BigIntegerField()),
                ('gpu_info', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '节点当前状态',
                'verbose_name_plural': '节点当前状态列表',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeMetricArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_percent', models.FloatField()),
                ('memory_used', models.BigIntegerField()),
                ('memory_total', models.BigIntegerField()),
                ('gpu_info', models.JSONField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_archives', to='Araneae_manager.node')),
            ],
            options={
                'verbose_name': '节点指标归档',
                'verbose_name_plural': '节点指标归档列表',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('once', 'Once'), ('recurring', 'Recurring')], max_length=10)),
                ('order', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Araneae_main.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('node_hash', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('celery_label', models.CharField(max_length=200)),
                ('args', models.TextField(blank=True, null=True)),
                ('kwargs', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_task_relation', to='django_celery_beat.periodictask')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Araneae_manager.schedule')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Araneae_main.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='ChainedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('next_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_tasks', to='Araneae_manager.task')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_tasks', to='Araneae_manager.task')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Araneae_manager.taskchain')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('error', 'Error'), ('timeout', 'Timeout'), ('failed', 'Failed'), ('retry', 'Retry')], max_length=20)),
                ('task_result', models.TextField(blank=True, null=True)),
                ('task_created_at', models.DateTimeField(auto_now_add=True)),
                ('task_updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='Araneae_manager.node')),
            ],
        ),
    ]
