# Generated by Django 5.0.7 on 2025-05-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Araneae_main', '0001_initial'),
        ('Araneae_manager', '0001_initial'),
        ('Araneae_repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='Araneae_repo.project'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='Araneae_manager.schedule'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='Araneae_repo.version'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_records', to='Araneae_main.workplace'),
        ),
    ]
