services:
  controlnode:
    build:
      context: ./ControlNode
    env_file:
      - ./.env
    ports:
      - "8107:8000"
    environment:
      DJANGO_MIGRATE: "1"
    volumes:
      - controlnode-data:/data
      - controlnode-media:/app/media
      - controlnode-repo:/app/Araneae_repo/repo
    depends_on:
      - rabbitmq

  controlnode-worker:
    build:
      context: ./ControlNode
    env_file:
      - ./.env
    command: ["celery", "-A", "Araneae", "worker", "-l", "info"]
    environment:
      DJANGO_MIGRATE: "0"
    volumes:
      - controlnode-data:/data
    depends_on:
      - rabbitmq
      - controlnode

  controlnode-beat:
    build:
      context: ./ControlNode
    env_file:
      - ./.env
    command:
      [
        "celery",
        "-A",
        "Araneae",
        "beat",
        "-l",
        "info",
        "--scheduler",
        "django_celery_beat.schedulers:DatabaseScheduler"
      ]
    environment:
      DJANGO_MIGRATE: "0"
    volumes:
      - controlnode-data:/data
    depends_on:
      - rabbitmq
      - controlnode

  executionnode:
    build:
      context: ./ExecutionNode
    env_file:
      - ./.env
    ports:
      - "4107:5001"
    volumes:
      - executionnode-data:/data
      - executionnode-logs:/app/logs
    depends_on:
      - rabbitmq

  front:
    build:
      context: ./Front
    env_file:
      - ./.env
    ports:
      - "5109:80"
    depends_on:
      - controlnode

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: araneae
      RABBITMQ_DEFAULT_PASS: araneae

volumes:
  controlnode-data:
  controlnode-media:
  controlnode-repo:
  executionnode-data:
  executionnode-logs:
