# Generated by Django 5.0.7 on 2025-05-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Araneae_main', '0001_initial'),
        ('Araneae_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_hash', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('command', models.TextField()),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('changelog', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Araneae_main.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_hash', models.CharField(max_length=50, unique=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('entrance_file', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='Araneae_repo.project')),
            ],
            options={
                'ordering': ['-release_date'],
                'unique_together': {('project', 'version_hash')},
            },
        ),
        migrations.CreateModel(
            name='NodeProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_versions', to='Araneae_manager.node')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_projects', to='Araneae_repo.project')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_versions', to='Araneae_repo.version')),
            ],
        ),
    ]
