"""
Django settings for Araneae project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from config_loader import load_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_CONFIG = load_config()
_DJANGO = _CONFIG.get('django', {})
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or os.environ.get('SECRET_KEY') or _DJANGO.get('secret_key', 'dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
_debug_raw = os.environ.get('DJANGO_DEBUG', os.environ.get('DEBUG', _DJANGO.get('debug', True)))
DEBUG = str(_debug_raw).lower() in ('1', 'true', 'yes', 'on')

_allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', os.environ.get('ALLOWED_HOSTS', ''))
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = _DJANGO.get('allowed_hosts', ["*"])
_FRONTEND = _CONFIG.get('frontend', {})
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', _FRONTEND.get('base_url', 'http://localhost:5109'))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'Araneae_main',
    'Araneae_manager',
    'Araneae_repo',
    'drf_spectacular',
    'django_celery_beat',
    'django_celery_results',  # Optional, for task results storage
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Araneae.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Araneae.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH') or (BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:4173',
    'http://localhost:5173',
    'http://localhost:8080',
    'http://localhost:5109',
]  # 添加前端地址，csrf保护放行。
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:4173',
    'http://localhost:5173',
    'http://localhost:8080',
    'http://localhost:5109',
]  # 添加前端地址，csrf保护放行。

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#DRF settings

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    #'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'PAGE_SIZE' : 50,
    'DATE_FORMAT' : '%Y-%m-%d %H:%M:%S',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES' : [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=43200),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# 添加 repo 目录路径
REPO_DIR = os.path.join(BASE_DIR, 'Araneae_repo', 'repo')
os.makedirs(REPO_DIR, exist_ok=True)

# Celery settings (will be rebuilt after RabbitMQ config if available)
CELERY_BROKER_URL = 'amqp://guest@localhost//'
CELERY_RESULT_BACKEND = 'rpc://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# RabbitMQ settings (loaded from shared config.json or environment)
_RABBIT = _CONFIG.get('rabbitmq', {})
RABBITMQ = {
    'HOST': os.environ.get('RABBITMQ_HOST', _RABBIT.get('host', 'localhost')),
    'PORT': int(os.environ.get('RABBITMQ_PORT', _RABBIT.get('port', 5672))),
    'USERNAME': os.environ.get('RABBITMQ_USERNAME', _RABBIT.get('username', 'guest')),
    'PASSWORD': os.environ.get('RABBITMQ_PASSWORD', _RABBIT.get('password', '')),
    'VHOST': os.environ.get('RABBITMQ_VHOST', _RABBIT.get('vhost', '/')),
}

# Rebuild CELERY_BROKER_URL if pieces are available
if all(RABBITMQ.get(k) not in (None, '') for k in ('USERNAME','PASSWORD','HOST','PORT','VHOST')):
    CELERY_BROKER_URL = 'amqp://{username}:{password}@{host}:{port}/{vhost}'.format(
        username=RABBITMQ['USERNAME'],
        password=RABBITMQ['PASSWORD'],
        host=RABBITMQ['HOST'],
        port=RABBITMQ['PORT'],
        vhost=RABBITMQ['VHOST'],
    )

SPECTACULAR_SETTINGS = {
    'TITLE': 'Araneae API 文档',
    'DESCRIPTION': 'API 文档描述',
    'VERSION': '1.0.0',
    # 其他可选配置
}

INIT_ADMIN_USERNAME = _DJANGO.get('init_admin_username', 'admin')
INIT_ADMIN_EMAIL = _DJANGO.get('init_admin_email', 'admin@example.com')
INIT_ADMIN_USERNAME = os.environ.get('INIT_ADMIN_USERNAME', INIT_ADMIN_USERNAME)
INIT_ADMIN_EMAIL = os.environ.get('INIT_ADMIN_EMAIL', INIT_ADMIN_EMAIL)
INIT_ADMIN_PASSWORD = os.environ.get(
    'INIT_ADMIN_PASSWORD',
    _DJANGO.get('init_admin_password', 'changeme123'),
)

MODE = 'dev'  # 'dev' or 'prod'

_BASALTPASS = _CONFIG.get('basaltpass', {})
_BASALTPASS_OAUTH = _BASALTPASS.get('oauth', {})
_BASALTPASS_BASE_URL = os.environ.get('BASALTPASS_BASE_URL', _BASALTPASS.get('base_url', 'http://localhost:8101')).rstrip('/')
_DEFAULT_DISCOVERY_URL = f"{_BASALTPASS_BASE_URL}/api/v1/.well-known/openid-configuration"

BASALTPASS_OAUTH = {
    'ENABLED': os.environ.get('BASALTPASS_OAUTH_ENABLED', str(_BASALTPASS_OAUTH.get('enabled', True))).lower() in ('1', 'true', 'yes'),
    'DISCOVERY_URL': os.environ.get('BASALTPASS_OAUTH_DISCOVERY_URL', _BASALTPASS_OAUTH.get('discovery_url', _DEFAULT_DISCOVERY_URL)),
    'CLIENT_ID': os.environ.get('BASALTPASS_OAUTH_CLIENT_ID', _BASALTPASS_OAUTH.get('client_id', '')),
    'CLIENT_SECRET': os.environ.get('BASALTPASS_OAUTH_CLIENT_SECRET', _BASALTPASS_OAUTH.get('client_secret', '')),
    'REDIRECT_URI': os.environ.get('BASALTPASS_OAUTH_REDIRECT_URI', _BASALTPASS_OAUTH.get('redirect_uri', 'http://localhost:8107/api/auth/basaltpass/callback/')),
    'SCOPE': os.environ.get('BASALTPASS_OAUTH_SCOPE', _BASALTPASS_OAUTH.get('scope', 'openid profile email offline_access')),
    'FRONTEND_CALLBACK_PATH': os.environ.get('BASALTPASS_FRONTEND_CALLBACK_PATH', _BASALTPASS_OAUTH.get('frontend_callback_path', '/oauth/callback')),
}

_SECURITY = _CONFIG.get('security', {})
CALLBACK_SHARED_SECRET = os.environ.get('ARANEAE_CALLBACK_SHARED_SECRET', _SECURITY.get('callback_shared_secret', ''))
NODE_API_TOKEN = os.environ.get('ARANEAE_NODE_API_TOKEN', _SECURITY.get('node_api_token', ''))

